# Travis-CI testing for Aveaux Project
language: go

# Versions to test
go:
    - 1.3

install:
    - go get github.com/onsi/ginkgo/ginkgo
    - go get github.com/onsi/gomega

# Testing script to exec
script:
    - go test -v ./...

# Configure notifications
notifications:
    email:
        recipients:
            - benjamin@bengfort.com
            - will@willz.org
        on_success: change
        on_failure: always
